micronaut:
  application:
    name: grpcCrud
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/products
#flyway:
#  datasources:
#    default:
#      enabled: true
jpa:
  default:
    entity-scan:
      packages: 'com.example.adapter.db'
      enabled: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
